extends Node

const COR_DICT = {
	"gray": Color.GRAY,
	"red": Color.RED,
	"green": Color.GREEN,
	"blue": Color.BLUE,
	"yellow": Color.YELLOW,
	"orange": Color.ORANGE,
	"pink": Color.PINK,
	"white": Color.WHITE,
}

const CIDADES = [
	"Atlanta", "Boston", "Calgary", "Charleston", "Chicago", "Dallas", "Denver",
	"Duluth", "El Paso", "Helena", "Houston", "Kansas City", "Las Vegas", "Little Rock",
	"Los Angeles", "Miami", "Montreal", "Nashville", "New Orleans", "New York",
	"Oklahoma City", "Omaha", "Phoenix", "Pittsburgh", "Portland", "Raleigh",
	"Salt Lake City", "San Francisco", "Santa Fe", "Sault Ste. Marie", "Seattle",
	"St. Louis", "Toronto", "Vancouver", "Washington", "Winnipeg"
]

const ROTAS = [
	["Seattle", "Portland", "gray", 1],
	["Seattle", "Helena", "yellow", 6],
	["Seattle", "Calgary", "gray", 4],
	["Portland", "San Francisco", "green", 5],
	["Portland", "Salt Lake City", "blue", 6],
	["San Francisco", "Salt Lake City", "orange", 5],
	["San Francisco", "Los Angeles", "pink", 3],
	["Los Angeles", "Las Vegas", "gray", 2],
	["Los Angeles", "Phoenix", "gray", 3],
	["Los Angeles", "El Paso", "black", 6],
	["Las Vegas", "Salt Lake City", "orange", 3],
	["Salt Lake City", "Helena", "pink", 3],
	["Salt Lake City", "Denver", "red", 3],
	["Helena", "Calgary", "gray", 4],
	["Helena", "Winnipeg", "blue", 4],
	["Helena", "Duluth", "orange", 6],
	["Helena", "Denver", "green", 4],
	["Helena", "Omaha", "red", 5],
	["Calgary", "Winnipeg", "white", 6],
	["Winnipeg", "Duluth", "black", 4],
	["Winnipeg", "Sault Ste. Marie", "gray", 6],
	["Duluth", "Sault Ste. Marie", "gray", 3],
	["Duluth", "Omaha", "gray", 2],
	["Duluth", "Chicago", "red", 3],
	["Omaha", "Denver", "pink", 4],
	["Omaha", "Kansas City", "gray", 1],
	["Omaha", "Chicago", "blue", 4],
	["Chicago", "Toronto", "white", 4],
	["Chicago", "Pittsburgh", "orange", 3],
	["Chicago", "St. Louis", "green", 2],
	["Toronto", "Montreal", "gray", 3],
	["Toronto", "Pittsburgh", "gray", 2],
	["Montreal", "Boston", "gray", 2],
	["Boston", "New York", "red", 2],
	["New York", "Washington", "orange", 2],
	["New York", "Pittsburgh", "white", 2],
	["Washington", "Raleigh", "gray", 2],
	["Washington", "Pittsburgh", "gray", 2],
	["Raleigh", "Atlanta", "gray", 2],
	["Raleigh", "Charleston", "gray", 2],
	["Atlanta", "Charleston", "gray", 2],
	["Atlanta", "Nashville", "gray", 1],
	["Atlanta", "Miami", "blue", 5],
	["Atlanta", "New Orleans", "yellow", 4],
	["New Orleans", "Houston", "red", 2],
	["New Orleans", "Little Rock", "green", 3],
	["Little Rock", "Nashville", "white", 3],
	["Little Rock", "St. Louis", "gray", 2],
	["Little Rock", "Dallas", "gray", 2],
	["Dallas", "Houston", "gray", 1],
	["Dallas", "El Paso", "red", 4],
	["Dallas", "Oklahoma City", "gray", 2],
	["Houston", "El Paso", "green", 6],
	["El Paso", "Phoenix", "white", 3],
	["El Paso", "Santa Fe", "gray", 2],
	["El Paso", "Denver", "green", 4],
	["Santa Fe", "Denver", "gray", 2],
	["Santa Fe", "Oklahoma City", "blue", 3],
	["Oklahoma City", "Denver", "red", 4],
	["Oklahoma City", "Kansas City", "gray", 2],
	["Kansas City", "St. Louis", "blue", 2],
	["St. Louis", "Chicago", "white", 2],
	["St. Louis", "Nashville", "gray", 2],
	["Nashville", "Pittsburgh", "yellow", 4],
	["Pittsburgh", "New York", "green", 2]
]
