extends Node

const COR_DICT = {
	"gray": Color.GRAY,
	"red": Color.RED,
	"green": Color.GREEN,
	"blue": Color.BLUE,
	"yellow": Color.YELLOW,
	"orange": Color.ORANGE,
	"pink": Color.PINK,
	"white": Color.WHITE,
	"black": Color.BLACK,
}

const CIDADES = [
	"Atlanta", "Boston", "Calgary", "Charleston", "Chicago", "Dallas", "Denver",
	"Duluth", "El Paso", "Helena", "Houston", "Kansas City", "Las Vegas", "Little Rock",
	"Los Angeles", "Miami", "Montreal", "Nashville", "New Orleans", "New York",
	"Oklahoma City", "Omaha", "Phoenix", "Pittsburgh", "Portland", "Raleigh",
	"Salt Lake City", "San Francisco", "Santa Fe", "Sault St Marie", "Seattle",
	"Saint Louis", "Toronto", "Vancouver", "Washington", "Winnipeg"
]

# Primeira cidade = mais acima, Segunda cidade = mais abaixo
const ROTAS = [
	["Montreal", "Sault St Marie", "black", 5],
	["Montreal", "Toronto", "gray", 3],
	["Montreal", "Boston", "gray", 2],
	["Montreal", "Boston", "gray", 2],
	["Montreal", "New York", "blue", 2],
	["Calgary", "Vancouver", "gray", 3],
	["Calgary", "Seattle", "gray", 4],
	["Calgary", "Helena", "gray", 4],
	["Calgary", "Winnipeg", "white", 6],
	["Winnipeg", "Helena", "blue", 4],
	["Winnipeg", "Duluth", "black", 4],
	["Winnipeg", "Sault St Marie", "gray", 6],
	["Vancouver", "Seattle", "gray", 1],
	["Vancouver", "Seattle", "gray", 1],
	["Boston", "New York", "yellow", 2],
	["Boston", "New York", "red", 2],
	["Sault St Marie", "Toronto", "gray", 2],
	["Sault St Marie", "Duluth", "gray", 3],
	["Seattle", "Portland", "gray", 1],
	["Seattle", "Portland", "gray", 1],
	["Seattle", "Helena", "yellow", 6],
	["Toronto", "Duluth", "pink", 6],
	["Toronto", "Chicago", "white", 4],
	["Toronto", "Pittsburgh", "gray", 2],
	["Portland", "San Francisco", "green", 5],
	["Portland", "San Francisco", "pink", 5],
	["Portland", "Salt Lake City", "blue", 6],
	["Duluth", "Helena", "orange", 6],
	["Duluth", "Omaha", "gray", 2],
	["Duluth", "Omaha", "gray", 2],
	["Duluth", "Chicago", "red", 3],
	["New York", "Pittsburgh", "white", 2],
	["New York", "Pittsburgh", "green", 2],
	["New York", "Washington", "orange", 2],
	["New York", "Washington", "black", 2],
	["Helena", "Salt Lake City", "pink", 3],
	["Helena", "Denver", "green", 4],
	["Helena", "Omaha", "red", 5],
	["Pittsburgh", "Chicago", "orange", 3],
	["Pittsburgh", "Chicago", "black", 3],
	["Pittsburgh", "Saint Louis", "green", 5],
	["Pittsburgh", "Nashville", "yellow", 4],
	["Pittsburgh", "Raleigh", "gray", 2],
	["Pittsburgh", "Washington", "gray", 2],
	["Chicago", "Omaha", "blue", 4],
	["Chicago", "Saint Louis", "green", 2],
	["Chicago", "Saint Louis", "white", 2],
	["Washington", "Raleigh", "gray", 2],
	["Washington", "Raleigh", "gray", 2],
	["Omaha", "Denver", "pink", 4],
	["Omaha", "Kansas City", "gray", 1],
	["Omaha", "Kansas City", "gray", 1],
	["Salt Lake City", "San Francisco", "orange", 5],
	["Salt Lake City", "San Francisco", "white", 5],
	["Salt Lake City", "Las Vegas", "orange", 3],
	["Salt Lake City", "Denver", "red", 3],
	["Salt Lake City", "Denver", "yellow", 3],
	["Kansas City", "Denver", "black", 4],
	["Kansas City", "Denver", "orange", 4],
	["Kansas City", "Oklahoma City", "gray", 2],
	["Kansas City", "Oklahoma City", "gray", 2],
	["Kansas City", "Saint Louis", "blue", 2],
	["Kansas City", "Saint Louis", "pink", 2],
	["Saint Louis", "Little Rock", "gray", 2],
	["Saint Louis", "Nashville", "gray", 2],
	["Raleigh", "Nashville", "black", 3],
	["Raleigh", "Atlanta", "gray", 2],
	["Raleigh", "Atlanta", "gray", 2],
	["Raleigh", "Charleston", "gray", 2],
	["Denver", "Phoenix", "white", 5],
	["Denver", "Santa Fe", "gray", 2],
	["Raleigh", "Oklahoma City", "red", 4],
	["Nashville", "Little Rock", "white", 3],
	["Nashville", "Atlanta", "gray", 1],
	["San Francisco", "Los Angeles", "pink", 3],
	["San Francisco", "Los Angeles", "yellow", 3],
	["Atlanta", "New Orleans", "yellow", 4],
	["Atlanta", "New Orleans", "orange", 4],
	["Atlanta", "Miami", "blue", 5],
	["Atlanta", "Charleston", "gray", 2],
	["Charleston", "Miami", "pink", 4],
	["Oklahoma City", "Santa Fe", "blue", 3],
	["Oklahoma City", "El Paso", "yellow", 5],
	["Oklahoma City", "Dallas", "gray", 2],
	["Oklahoma City", "Dallas", "gray", 2],
	["Oklahoma City", "Little Rock", "gray", 2],
	["Little Rock", "Dallas", "gray", 2],
	["Little Rock", "New Orleans", "green", 3],
	["Las Vegas", "Los Angeles", "gray", 2],
	["Santa Fe", "Phoenix", "gray", 3],
	["Santa Fe", "El Paso", "gray", 2],
	["Los Angeles", "Phoenix", "gray", 3],
	["Los Angeles", "El Paso", "black", 6],
	["Phoenix", "El Paso", "gray", 3],
	["Dallas", "El Paso", "red", 4],
	["Dallas", "Houston", "gray", 1],
	["Dallas", "Houston", "gray", 1],
	["El Paso", "Houston", "green", 6],
	["New Orleans", "Houston", "gray", 2],
	["New Orleans", "Miami", "red", 6],
]
